# Generated by Django 3.2 on 2021-04-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('iso_code', models.CharField(blank=True, max_length=3, null=True)),
                ('date', models.DateField()),
                ('total_vaccinations', models.IntegerField(blank=True, null=True)),
                ('people_vaccinated', models.IntegerField(blank=True, null=True)),
                ('people_fully_vaccinated', models.IntegerField(blank=True, null=True)),
                ('daily_vaccinations_raw', models.IntegerField(blank=True, null=True)),
                ('daily_vaccinations', models.IntegerField(blank=True, null=True)),
                ('total_vaccinations_per_hundred', models.FloatField(blank=True, null=True)),
                ('people_vaccinated_per_hundred', models.FloatField(blank=True, null=True)),
                ('people_fully_vaccinated_per_hundred', models.FloatField(blank=True, null=True)),
                ('daily_vaccinations_per_million', models.IntegerField(blank=True, null=True)),
                ('vaccines', models.CharField(blank=True, max_length=200, null=True)),
                ('source_name', models.CharField(blank=True, max_length=200, null=True)),
                ('source_website', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
